spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/renovar?ssl=false
    username: app_renovar
    password: app_renovar
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  application:
    name: renovar

api:
  security:
    token:
      secret  : ${JWT_SECRET:my-secret-key}