spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/renovar?ssl=false
    username: app_renovar
    password: app_renovar
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: update
  jackson:
    default-property-inclusion: non_null
  application:
    name: renovar
api:
  security:
    token:
      secret  : ${JWT_SECRET:my-secret-key}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
#logging:
#  level:
#    root: DEBUG
#    org:
#      hibernate:
#        sql: DEBUG
#        type:
#          descriptor:
#            sql: TRACE
#      springframework:
#        web: DEBUG
#        security: DEBUG
#        data: DEBUG
#        jpa: DEBUG
#        hibernate: DEBUG
#        jackson: DEBUG