CREATE TABLE tb_endereco(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua VARCHAR(80),
    numero varchar(80),
    bairro VARCHAR(80),
    cidade VARCHAR(80) NOT NULL,
    estado VARCHAR(80) NOT NULL,
    cep VARCHAR(20) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL
);