CREATE TABLE tb_obra(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_prestante VARCHAR(80) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    status varchar(45) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL,
    endereco_id INT NOT NULL,
    CONSTRAINT fk_obra_endereco FOREIGN KEY(endereco_id) REFERENCES tb_endereco(id)
);