CREATE TABLE tb_funcionario(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR(20) NOT NULL UNIQUE,
    nome VARCHAR(80) NOT NULL,
    cpf VARCHAR(20) NOT NULL UNIQUE,
    registro_geral VARCHAR(20) NOT NULL UNIQUE,
    data_nascimento DATE NOT NULL,
    salario_hora DECIMAL(10,2) NOT NULL,
    funcao_id INT NOT NULL,
    endereco_id INT NOT NULL,
    status varchar(45) NOT NULL,
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_funcionario_funcao FOREIGN KEY(funcao_id) REFERENCES tb_funcao(id),
    CONSTRAINT fk_funcionario_endereco FOREIGN KEY(endereco_id) REFERENCES tb_endereco(id)
);
