CREATE TABLE tb_ferramenta(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(80) NOT NULL,
    data_compra varchar(80),
    status VARCHAR(80),
    valor_unitario DECIMAL(10,2),
    creation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL
);